# Generated by Django 4.2.11 on 2024-11-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_alter_patient_doctor'),
    ]

    operations = [
    ]
